"""Profile exporter — generates CLAUDE.md content from dimensional profiles.

Translates raw dimension profiles into actionable working guidelines
that Claude reads at the start of every session.
"""

import json
from pathlib import Path
from typing import Optional

from ..data.dimensions import get_all_profiles
from .llm import call_claude, parse_json_response


GUIDELINES_PROMPT = """You have 5 dimensional profiles of a person named Abhishek, built from observing his conversations with Claude over time. Generate actionable working guidelines that would help a future Claude session work with him more effectively.

Profiles:
{profiles}

Generate 6-8 concrete, specific guidelines. Not platitudes — real behavioral instructions based on the profiles.

Respond with JSON:
{{
  "guidelines": [
    "Guideline text — specific and actionable"
  ],
  "one_liner": "A single sentence that captures who this person is to work with"
}}

Rules:
- Each guideline should change how Claude responds in a concrete situation
- Reference actual patterns (e.g., 'When he says make it generic mid-build, the specific thing was a pretext')
- No generic advice like 'be concise' — only things derived from HIS specific patterns
- Write in imperative voice addressed to Claude"""


MARKER = "# Dimensional Profile (auto-generated by Claude Desk)"


def generate_profile_block() -> str:
    """Generate a CLAUDE.md block from current dimensional profiles."""
    profiles = get_all_profiles()
    if not profiles:
        return ""

    # Build the summary section
    lines = [MARKER, ""]

    for p in profiles:
        dim = p["dimension"].capitalize()
        summary = p["summary"]
        trajectory = p["trajectory"]
        lines.append(f"**{dim}**: {summary}")
        if trajectory:
            lines.append(f"  *Trajectory: {trajectory}*")
        lines.append("")

    # Generate actionable guidelines via LLM
    profiles_text = "\n\n".join(
        f"**{p['dimension'].capitalize()}**: {p['summary']}\n"
        f"Profile: {json.dumps(p['profile'], indent=2)}\n"
        f"Trajectory: {p['trajectory']}"
        for p in profiles
    )

    result = call_claude(GUIDELINES_PROMPT.format(profiles=profiles_text))
    if result:
        parsed = parse_json_response(result)
        if parsed:
            guidelines = parsed.get("guidelines", [])
            one_liner = parsed.get("one_liner", "")

            if one_liner:
                lines.insert(2, f"*{one_liner}*")
                lines.insert(3, "")

            if guidelines:
                lines.append("## Working Guidelines")
                lines.append("")
                for g in guidelines:
                    lines.append(f"- {g}")
                lines.append("")

    return "\n".join(lines)


def apply_profile_to_claude_md() -> bool:
    """Write the dimensional profile to ~/.claude/CLAUDE.md."""
    block = generate_profile_block()
    if not block:
        return False

    claude_md = Path.home() / ".claude" / "CLAUDE.md"

    try:
        existing = claude_md.read_text() if claude_md.exists() else ""

        # Remove old block if present
        if MARKER in existing:
            before = existing[:existing.index(MARKER)].rstrip()
            after_start = existing.index(MARKER)
            remaining = existing[after_start:]
            # Find next top-level heading
            next_heading = remaining.find("\n# ", 1)
            if next_heading >= 0:
                after = remaining[next_heading:]
            else:
                after = ""
            existing = (before + "\n\n" + after).strip()

        # Append new block
        new_content = existing + "\n\n" + block + "\n"
        claude_md.write_text(new_content)
        print("  CLAUDE.md dimensional profile updated")
        return True
    except Exception as e:
        print(f"  Failed to update CLAUDE.md: {e}")
        return False


def get_profile_preview() -> str:
    """Return the profile block as a string for preview (without writing to disk)."""
    return generate_profile_block()
